pub mod chat;
pub mod personnality;

pub use chat::{
    CHAT_PROMPT, CONTEXT_PART_PROMPT, EMOTION_STATE_PART_PROMPT, MEMORY_RETRIEVE_PART_PROMPT,
    SIGNIFICANT_MEMORY_PART_PROMPT, WRITING_STYLE_PART_PROMPT,
};
pub use personnality::WRITING_STYLE_PROMPT;
